### ISSUE TITLE
Raft WSL insists to offer free period and then pay for a subscription while I have already paid

### ISSUE THREAD

**Issue by xprzemekw** [WhitewaterFoundry/Raft-WSL-Feedback#1]
Raft WSL insists to offer free period and then pay for a subscription while I have already paid.
In addition Settings -> Subscription tries to work out subscription status but it never completes and shows 'Inactive'.

**Comment by crramirez** [comment]
Hello,

Thanks for writing to us. Please forward your purchase confirmation email to contact@whitewaterfoundry.com, also if you can, a screenshot showing your Raft Subscription in your Microsoft account page.


Regards,
Carlos

**Comment by crramirez** [comment]
Hello,

We published a version with one correction that should fix your issue.

Try again.

Thanks for reporting

**Comment by xprzemekw** [comment]
Hi,

In have forwarded necessary details to contact@whitewaterfoundry.com. Unfortunately issue still occurs for me.

![image](https://user-images.githubusercontent.com/9196393/87056288-b1183480-c205-11ea-9d6a-99ed9e24bc3f.png)

![image](https://user-images.githubusercontent.com/9196393/87056418-e1f86980-c205-11ea-9add-9d7067abbbf9.png)
