### ISSUE TITLE
App launch failure - Event 1000 Application error - Windows 11 22H2 Build 22624.1690

### ISSUE THREAD

**Issue by mikenelson-io** [WhitewaterFoundry/Raft-WSL-Feedback#32]
- Install RAFT from Windows Store.
- Launch RAFT from Start menu link.
- UI opens briefly, then closes.

Application Log Event 1000:
```
Faulting application name: RaftUWP.exe, version: 1.0.0.0, time stamp: 0x642d69eb
Faulting module name: twinapi.appcore.dll, version: 10.0.22621.1690, time stamp: 0x678c16ac
Exception code: 0xc000027b
Fault offset: 0x00000000000c07f3
Faulting process id: 0x0x7320
Faulting application start time: 0x0x1D981B3E437A3CC
Faulting application path: C:\Program Files\WindowsApps\WhitewaterFoundry.Raft-WSL_23.4.0.0_x64__r1wwvvmhjq692\RaftUWP.exe
Faulting module path: C:\WINDOWS\SYSTEM32\twinapi.appcore.dll
Report Id: e84d04b2-337a-49d7-90e6-3d9e09523019
Faulting package full name: WhitewaterFoundry.Raft-WSL_23.4.0.0_x64__r1wwvvmhjq692
Faulting package-relative application ID: App
```
Application Log Event 1001:
```
Fault bucket 1545560374038598048, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: WhitewaterFoundry.Raft-WSL_23.4.0.0_x64__r1wwvvmhjq692
P2: praid:App
P3: 1.0.0.0
P4: 642d69eb
P5: combase.dll
P6: 10.0.22621.1537
P7: 64a5794c
P8: 80070005
P9: 000000000009200b
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8fb7b5c5-02b3-43f2-93c1-f41c5844fdf2.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4aa9cad1-03f4-465f-8b01-b52c6c1c178b.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.016b9cc3-f7bf-4361-bb0e-f4560efe5ca3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c9bcb7fc-873c-444a-8277-91b1d8e320d4.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4f729cb0-b92b-4bb8-8645-3302c04651be.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_WhitewaterFoundr_b98e6ce98e67c547be7cfb534a9e44058557f49_fdfc3be3_7996e1b0-8c73-42d0-8cde-098f7adc48d6

Analysis symbol: 
Rechecking for solution: 0
Report Id: e84d04b2-337a-49d7-90e6-3d9e09523019
Report Status: 268435456
Hashed bucket: 36e5559a677f080f0572eef8b17d91a0
Cab Guid: 0
```

**Comment by crramirez** [comment]
Hello @mikenelson-io ,

Thanks for reporting it. I have seen this a couple of times and regularly it get solved by restarting Windows. It happens when it cannot connect to the Microsoft Store. But you can also check your system with https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e .

Tell me if you can solve the problem

Best Regards,
Carlos

**Comment by mikenelson-io** [comment]
Running the DISM and SFC commands, as well as rebooting several times, has not fixed the issue.
Also, fails on Win 11 22H2 22624.1680 build.

**Comment by crramirez** [comment]
Could you please send me an email to contact@whitewaterfoundry.com? so we can explore other options.

Regards
