### ISSUE TITLE
 getting stuck on win10

### ISSUE THREAD

**Issue by NightmareZero** [WhitewaterFoundry/Raft-WSL-Feedback#34]
the app seems to be getting stuck and I'm unable to proceed further.

![error](https://github.com/WhitewaterFoundry/Raft-WSL-Feedback/assets/17422155/fab8fd0a-aeca-4f6f-9557-b97e5d0ef86e)

I'm not sure if this is a known issue or if there's a fix available, but I thought it was important to bring it to your attention. If you have any suggestions or updates on when this might be resolved, I would greatly appreciate it.

![version](https://github.com/WhitewaterFoundry/Raft-WSL-Feedback/assets/17422155/69816539-90fe-47f0-95b9-3ccfbe498f45)

**Comment by NightmareZero** [comment]
where can I get the logs for you ?

**Comment by crramirez** [comment]
Hello,

This usually happens when the `wsl` command get stuck too. One remedy is to restart Windows another:

```
wsl --shutdown
```
One question do you use any JerBrains IDEs?

**Comment by NightmareZero** [comment]
> 
I use VSCode, but I have Intellij installed.

**Comment by NightmareZero** [comment]
> Hello,
> 
> This usually happens when the `wsl` command get stuck too. One remedy is to restart Windows another:
> 
> ```
> wsl --shutdown
> ```
> 
> One question do you use any JerBrains IDEs?


I use VSCode, but I have Intellij installed.

**Comment by crramirez** [comment]
I asked because Intellij at launch, executes every distro that you have installed and with the Store edition of WSL this causes this behavior. And you need to deactivate this JDK WSL scan. But if you don't use it, the problem is another thing. 

Could you solve the problem?

**Comment by NightmareZero** [comment]
> I asked because Intellij at launch, executes every distro that you have installed and with the Store edition of WSL this causes this behavior. And you need to deactivate this JDK WSL scan. But if you don't use it, the problem is another thing.
> 
> Could you solve the problem?


I installed it, but hardly ever use it. every time I restart the system, Raft can open, but after a while it gets stuck on the startup page again.

**Comment by ghost** [comment]
This problem also occurs in windows11
I tried to uninstall fedora remix and ubuntu22.04.
And try to close/Uninstall/re-install WSL2.
But the problem remains `Getting distros...`

I am not very familiar with windows
So I don't know where to share the error log
If anyone knows please @ me

**Comment by ghost** [comment]
Found solution:
WSL2 is now installed from the Microsoft Store by default.
`Windows Subsystem for Linux` Uninstall this
and Installing WSL2 manually and installing a non-Microsoft Store version will fix this problem.
But I still hope the author can fix. Because if WSL2 is installed from Microsoft Store, the update speed will be faster.

**Comment by crramirez** [comment]
Yes, this is the solution that we have found. Uninstalling the Store version of WSL. Since this version shipped in beta it eventually stuck. We have seen how they have improved it but time to time it get stuck again.

The problem is that if you are in Windows 10, uninstalling it you'll lose even WSLg and if you want GUI you'll need to install an Xserver as before.

Raft depends entirely on the wsl.exe command. If it stop responding Raft will also. We can add some timeouts to Raft so, it can detect that WSL is stuck but it won't solve the problem.

The only thing that we have found to stop it happening is to stop any program that scans distributions, in out case is IntelliJ. If we disable the JVM scan on WSL the problem stop happening. Probably other tools are doing the same.

**Comment by crramirez** [comment]
Hello,

We are investigation on how improve Raft when this situation happens, so the app won't be indefinitely stuck and only behave slow but usable.

One question. When this happens you can still use the `wsl` command? If you issue a `wsl --list --verbose`:

1. It will give me the result instantaneous.
2. Give me the result after some seconds, less than 10
3. Give me the result after several seconds 15 or more
4. It will never give me the result.

We are trying to improve the situation for 2 & 3

**Comment by NightmareZero** [comment]
> Hello,
> 
> We are investigation on how improve Raft when this situation happens, so the app won't be indefinitely stuck and only behave slow but usable.
> 
> One question. When this happens you can still use the `wsl` command? If you issue a `wsl --list --verbose`:
> 
> 1. It will give me the result instantaneous.
> 2. Give me the result after some seconds, less than 10
> 3. Give me the result after several seconds 15 or more
> 4. It will never give me the result.
> 
> We are trying to improve the situation for 2 & 3

In fact, in the stuck state, this command can immediately return the result. I tried it 30 times per second for 30 seconds, and each time the result returned immediately.

```bash
➜  ~ wsl.exe --list --verbose
  NAME        STATE           VERSION
* Alpine      Running         1
  BuildO79    Running         2
  BuildO87    Running         2
  AlpServ     Running         2
```

**Comment by crramirez** [comment]
Hello,

We released a patched version of Raft that should improve the situation.

Give it a try and tell me if it improves.

Regards

**Comment by ghost** [comment]
> Hello,
> 
> We released a patched version of Raft that should improve the situation.
> 
> Give it a try and tell me if it improves.
> 
> Regards

@crramirez 
Thank you for update.
But unfortunately, the problem still exists.
my system is windows11.
and My WSL was installed locally, When I learned that the problem seemed to be solved. I tried to uninstall - remove WSL completely - restart my computer - re-download WSL from Microsoft Store.

**Comment by NightmareZero** [comment]
> > Hello,
> > We released a patched version of Raft that should improve the situation.
> > Give it a try and tell me if it improves.
> > Regards
> 
> @crramirez Thank you for update. But unfortunately, the problem still exists. my system is windows11. and My WSL was installed locally, When I learned that the problem seemed to be solved. I tried to uninstall - remove WSL completely - restart my computer - re-download WSL from Microsoft Store.

Unfortunately, it didn't fix my issue too. I'm using Windows 10 version 22H2.

**Comment by crramirez** [comment]
Hello @NightmareZero @1trapbox,

We released a new version with a huge change in how the distribution status is gathered from the WSL engine. It should be faster and use fewer resources. Also, it should address the stuck problem. 

Please give it a try: 23.10.1

Best Regards

**Comment by luoshengming** [comment]
I also have the same issue, the system version is Windows 23h2 and the software version is 23.11.1. Additionally, I don't think this issue has anything to do with Intellij, as I use it every day. However, this issue only appeared after a certain update to Raftwsl.

**Comment by rclilly** [comment]
I'm having this same issue on:
Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎06/‎20/‎23
OS build	22621.2715
Experience	Windows Feature Experience Pack 1000.22677.1000.0

I don't have any Jetbrains software installed.

**Comment by wgetnz** [comment]
I also have the same issue

**Comment by Kounavi** [comment]
I can concur I have the same issue in two different laptops using Win 11. I do have Jetbrains Toolbox installed but have noticed this behaviour even without it.

**Comment by crramirez** [comment]
Definitely the issue that we are fixing, is not the same that you are having. We are preparing a survey and improving Raft logging so you can help us to understand what is happening.

**Comment by crramirez** [comment]
Hello everyone,

Please could you fill the following survey? https://www.surveymonkey.com/r/WTKK629 

Also, when you are experiencing the behavior. Please go to the folder `%LOCALAPPDATA%\Packages\WhitewaterFoundry.Raft-WSL_r1wwvvmhjq692\LocalState\logs` for **Raft WSL** or `%LOCALAPPDATA%\Packages\WhitewaterFoundryLtd.Co.RaftWSL_kd1vv0z0vy70w\LocalState\logs` for **Raft WSL (L)** open the file **commands-log**_CURRENTDATE_ and copy its content here. Check if you have any private information and change or delete it (like your distro names, just in case)

This will help a lot to us to narrow the issue.

Regards,
Carlos

**Comment by wgetnz** [comment]
2023-12-12 10:05:40.679 +08:00 [INF] [STARTED] (27456) wsl --help
2023-12-12 10:05:40.889 +08:00 [INF] [ENDED]   (27456) wsl --help (-1): 版权所有(c) Microsoft Corporation。保留所有权利。 \n 有关此产品的隐私信息，请访问 https://aka.ms/privacy。 \n  \n 用法: wsl.exe [参数] [选项...][命令行] \n  \n 运行 Linux 二进制文件的参数:  \n  \n    如果未提供命令行，wsl.exe 将启动默认 shell。 \n  \n    --exec、-e <CommandLine> \n        在不使用默认 Linux shell 的情况下执行指定的命令。 \n  \n    --shell-type <standard|login|none> \n        使用提供的 shell 类型执行指定的命令。 \n  \n    -- \n        按时传递剩余的命令行。 \n  \n 选项: \n    --cd <Directory> \n        将指定目录设置为当前工作目录。 \n        如果使用 ~，则将使用 Linux 用户的主路径。如果路径开始于  \n        对于 /字符，它将解释为绝对 Linux 路径。 \n        否则，该值必须是绝对 Windows 路径。 \n  \n    --distribution，-d <Distro> \n        运行指定的分发版。 \n  \n    --user，-u <UserName> \n        以指定用户身份运行。 \n  \n    --system \n        为系统分发版启动 shell。 \n  \n 用于管理适用于 Linux 的 Windows 子系统的参数: \n  \n    --help \n        显示使用情况信息。 \n  \n    --debug-shell \n        出于诊断目的打开 WSL2 调试 shell。 \n  \n    --install [发行版] [选项...] \n        安装适用于 Linux 的 Windows 子系统分发版。 \n        有关有效分发版的列表，请使用“wsl.exe --list --online”。 \n  \n        选项: \n            --no-launch，-n \n                安装后不要启动分发版。 \n  \n            --web-download \n                从 Internet 而不是 Microsoft Store 下载分发版。 \n  \n            --no-distribution \n                仅安装所需的可选组件，不安装分发版。 \n  \n    --manage <Distro> <Options...> \n        更改发行版特定选项。 \n  \n        选项: \n            --set-sparse，-s <true|false> \n                将发行版的 vhdx 设置为稀疏，从而允许自动回收磁盘空间。 \n  \n    --mount <Disk> \n        在所有 WSL 2 分发版中附加和装载物理磁盘或虚拟磁盘。 \n  \n        选项: \n            --vhd \n                指定 <Disk> 引用虚拟硬盘。 \n  \n            --bare \n                将磁盘附加到 WSL2，但不要装载它。 \n  \n            --name <Name> \n                使用装入点的自定义名称装载磁盘。 \n  \n            --type <Type> \n                装载磁盘时要使用的文件系统(如果未指定)默认为 ext4。 \n  \n            --options <Options> \n                其他装载选项。 \n  \n            --partition <Index> \n                要装载的分区的索引(如果未指定)默认为整个磁盘。 \n  \n    --set-default-version <Version> \n        更改新分发版的默认安装版本。 \n  \n    --shutdown \n        立即终止所有正在运行的分发版和 WSL 2 \n        轻型实用工具虚拟机。 \n  \n    --status \n        显示适用于 Linux 的 Windows 子系统状态。 \n  \n    --unmount [磁盘] \n        从所有 WSL2 分发版中卸载和分离磁盘。 \n        如果在没有参数的情况下调用，则卸载和分离所有磁盘。 \n  \n    --update \n        更新适用于 Linux 的 Windows 子系统包。 \n  \n        选项: \n            --pre-release \n                下载预发行版本(如果可用)。 \n  \n    --version, -v \n        显示版本信息。 \n  \n 用于在适用于 Linux 的 Windows 子系统中管理分发版的参数: \n  \n    --export <Distro> <FileName> [选项] \n        将分发版导出到 tar 文件。 \n        文件名可以是 - 对于 stdout。 \n  \n        选项: \n            --vhd \n                指定应将分发版导出为 .vhdx 文件。 \n  \n    --import <Distro> <InstallLocation> <FileName> [选项] \n        将指定的 tar 文件作为新分发版导入。 \n        文件名可以是 - for stdin。 \n  \n        选项: \n            --version <版本> \n                指定要用于新分发的版本。 \n  \n            --vhd \n                指定所提供的文件是 .vhdx 文件，而不是 tar 文件。 \n                此操作在指定的安装位置创建 .vhdx 文件的副本。 \n  \n    --import-in-place <Distro> <FileName> \n        将指定的 .vhdx 文件作为新分发版导入。 \n        必须使用 ext4 文件系统类型设置此虚拟硬盘的格式。 \n  \n    --list, -l [选项] \n        列出分发版。 \n  \n        选项: \n            --all \n                列出所有分发版，包括分发版 \n                当前正在安装或卸载。 \n  \n            --running \n                仅列出当前正在运行的分发版。 \n  \n            --quiet，-q \n                仅显示分发版名称。 \n  \n            --verbose, -v \n                显示有关所版的详细信息。 \n  \n            --online，-o \n                显示适合通过“wsl --install”安装的可用分发版列表。 \n  \n    --set-default，-s <Distro> \n        将分布版设置为默认值。 \n  \n    --set-version <Distro> <Version> \n        更改指定分发版的版本。 \n  \n    --terminate, -t <Distro> \n        终止指定的分发版。 \n  \n    --unregister <Distro> \n        取消注册分发版并删除根文件系统。 \n 
2023-12-12 10:05:40.898 +08:00 [INF] [STARTED] (12036) wsl --version
2023-12-12 10:05:40.983 +08:00 [INF] [ENDED]   (12036) wsl --version (0): WSL 版本： 2.0.9.0 \n 内核版本： 5.15.133.1-1 \n WSLg 版本： 1.0.59 \n MSRDC 版本： 1.2.4677 \n Direct3D 版本： 1.611.1-81528511 \n DXCore 版本： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp \n Windows 版本： 10.0.22635.2850 \n 


版本	Windows 11 企业版
版本	23H2
安装日期	‎2023/‎11/‎8
操作系统版本	22635.2850
体验	Windows Feature Experience Pack 1000.22681.1000.0

no Jetbrains
